"""Let the unit tests run without a built ROS workspace.

`duburi_interfaces` is generated by colcon from the .msg/.action files, so it
only exists after a build and only inside a sourced ROS environment. Every
test module here transitively imports it (`duburi_control/__init__.py` pulls
in `duburi.py`, which imports `Move`), which meant the whole suite could only
be collected on a machine with ROS 2 installed -- including the tests that
exercise nothing but arithmetic.

When the real package is importable this file does nothing at all. When it is
not, a minimal stand-in is registered so the pure-Python logic can still be
tested. The stub carries the same field names as `Move.action`, so a test that
touches a field the real message does not have still fails.

This is a test-collection convenience, not a substitute for building the
workspace: anything that depends on real message serialisation, on rclpy, or
on the action machinery still needs a proper ROS run.
"""

import sys
import types


def _install_duburi_interfaces_stub() -> None:
    goal_fields = {
        'cmd': '', 'duration': 0.0, 'gain': 0.0, 'target': 0.0,
        'target_name': '', 'timeout': 0.0, 'settle': 0.0, 'yaw_rate_pct': 0.0,
        'camera': '', 'target_class': '', 'axes': '', 'deadband': 0.0,
        'kp_yaw': 0.0, 'kp_lat': 0.0, 'kp_depth': 0.0, 'kp_forward': 0.0,
        'target_bbox_h_frac': 0.0, 'visual_pid': False, 'on_lost': '',
        'stale_after': 0.0,
    }
    result_fields = {
        'success': False, 'message': '',
        'final_value': 0.0, 'error_value': 0.0,
    }
    feedback_fields = {
        'phase': '', 'current_value': 0.0,
        'error_value': 0.0, 'status_line': '',
    }

    def _rosidl_type(value):
        if isinstance(value, bool):
            return 'boolean'
        if isinstance(value, str):
            return 'string'
        return 'float'

    def _make(name, defaults):
        def __init__(self):
            for key, value in defaults.items():
                setattr(self, key, value)

        # rosidl generates this on every message class, and `commands.py`'s
        # test uses it to assert the COMMANDS registry cannot name a field
        # the action does not have. Without it here that check would be
        # skipped silently -- which is the one thing the check exists to
        # prevent.
        @classmethod
        def get_fields_and_field_types(cls):
            return {k: _rosidl_type(v) for k, v in defaults.items()}

        return type(name, (), {
            '__init__': __init__,
            '_fields': tuple(defaults),
            'get_fields_and_field_types': get_fields_and_field_types,
        })

    move = type('Move', (), {})
    move.Goal = _make('Goal', goal_fields)
    move.Result = _make('Result', result_fields)
    move.Feedback = _make('Feedback', feedback_fields)

    state = _make('DuburiState', {
        'header': None, 'armed': False, 'mode': '',
        'yaw_deg': 0.0, 'depth_m': 0.0, 'battery_voltage': 0.0,
    })

    pkg = types.ModuleType('duburi_interfaces')
    action = types.ModuleType('duburi_interfaces.action')
    msg = types.ModuleType('duburi_interfaces.msg')
    action.Move = move
    msg.DuburiState = state
    pkg.action = action
    pkg.msg = msg

    sys.modules.setdefault('duburi_interfaces', pkg)
    sys.modules.setdefault('duburi_interfaces.action', action)
    sys.modules.setdefault('duburi_interfaces.msg', msg)


try:
    import duburi_interfaces.action  # noqa: F401
except ImportError:
    _install_duburi_interfaces_stub()
